# Generated by Django 3.2.5 on 2021-07-29 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
